# Generated by Django 4.1.7 on 2023-02-28 08:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_vendor_date_created_alter_product_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="cover_image",
            field=models.ImageField(
                default="vendor_cover.jpg", upload_to=core.models.user_directory_path
            ),
        ),
    ]
