# Generated by Django 4.1.7 on 2023-02-28 08:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_vendor_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="cover_image",
            field=models.ImageField(
                default="vendor-header-bg.png",
                upload_to=core.models.user_directory_path,
            ),
        ),
    ]
