# Generated by Django 4.1.7 on 2023-02-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.CharField(default='100 Days', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(default='8', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='This is the product', max_length=100),
        ),
    ]
