# Generated by Django 4.1.7 on 2023-03-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_product_life_product_mfd_product_stock_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="life",
            field=models.CharField(
                blank=True, default="100 Days", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_count",
            field=models.CharField(blank=True, default="8", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True, default="This is the product", max_length=100, null=True
            ),
        ),
    ]
